name: Library updater for syrius

on:
  push:
    branches:
      - cicd
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lib-builder:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install -y unzip
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download libznn
        uses: robinraju/release-downloader@v1.6
        with:
          repository: "alienc0der/go-zenon"
          latest: true
      - name: Move libznn native library to blobs directory
        run: |
          tar -xvf libznn-linux-amd64.tar.gz
          mv libznn-linux-amd64.so lib/embedded_node/blobs/libznn.so
          tar -xvf libznn-darwin-universal.tar.gz
          mv libznn-darwin-universal.dylib lib/embedded_node/blobs/libznn.dylib
          unzip -j libznn-windows-amd64.zip -d ./
          mv libznn-windows-amd64.dll lib/embedded_node/blobs/libznn.dll
      - name: Check if there are changes
        run: |
          function check() {
            if [[ -z "$(git status --porcelain)" ]];
            then
              echo "0"
            else
              echo "1"
            fi
          }
          echo "CHANGED=$(check)" >> $GITHUB_ENV
      - name: Push if changes are present
        if: ${{ env.CHANGED == '1' }}
        run: |
          git config user.name  "Github Actions"
          git config user.email "GH-actions-ci@github.com"
          git add -f lib/embedded_node/blobs/*
          git commit -m "Updated native libraries"
          git push origin ${GITHUB_REF##*/}
